### ISSUE TITLE
Not showing containers

### ISSUE THREAD

**Issue by PhoenixtheII** [mike-mo/MoreTerra#10]
Reproduce:

1. V1.14 & terraria 1.3.4.4

2. Create new world (large) in terraria

3. Select only containers (all) in moreterra

4. Draw world

Results:
No markers are placed on image.

Expected.
Chests to be on the image.

**Comment by mike-mo** [comment]
I just created a new release, can you try that one and open a new issue if you find a problem? Thanks!

Link: https://github.com/mike-mo/MoreTerra/releases/tag/v1.16
