### ISSUE TITLE
1.3.5 error

### ISSUE THREAD

**Issue by SkeletonHunter96** [mike-mo/MoreTerra#11]
It seems that i am getting an error with opening maps with 1.3.5 worlds stating it cannot read past the end of the stream it is odd that it is only happening with some worlds and not others
![image](https://cloud.githubusercontent.com/assets/27862020/25288967/be26170a-2695-11e7-8de2-4f3dd8f6081c.png)

**Comment by TerabyteRex** [comment]
it happens when terraria is updated. any updated world would no longer work. will have to look at the changes.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by SkeletonHunter96** [comment]
alright thank you for your time in looking into the new changes :)

**Comment by tildetildetilde** [comment]
are you still looking into updating this?

**Comment by TerabyteRex** [comment]
I can fix it on monday. I would also like to know what features you would luke to see and What are your favorite parts of More Terra?
________________________________

**Comment by tildetildetilde** [comment]
my whole problem with it was that i couldnt get it to work at all. you
mentioned that the stream error happened because the program wasn't
compatible with the game's version, and since ive only gotten recently, it
hasn't been able to work at all. ill give more insight once i can make it
work, though!

**Comment by TerabyteRex** [comment]
fixed - uploading now. new version is 1.15

**Comment by TerabyteRex** [comment]
moreterra_binaries in top  level folder

**Comment by TerabyteRex** [comment]
actually use the release tab under code

**Comment by mike-mo** [comment]
Closing as per @TerabyteRex. Please open a new issue if this is still a problem.
