### ISSUE TITLE
Draw Map error

### ISSUE THREAD

**Issue by crai0519** [mike-mo/MoreTerra#12]
![untitled](https://user-images.githubusercontent.com/31704075/30124317-9e24d840-92e9-11e7-862e-641f635da9d0.png)

**Comment by mm64z** [comment]
I have this issue as well, with a world created earlier and opened/saved in 1.3.5, as well as a world created in 1.3.5. (MoreTerra v1.15)
Both of my worlds get to the 'Processing Npcs' step before getting this error.  They both only have the guide, with no housing.
Unchecking NPC markers allowed me to bypass this error.

**Comment by mike-mo** [comment]
Will track under #19 instead

**Comment by mike-mo** [comment]
See also #14
