### ISSUE TITLE
The giving key was not present in the dictionary.

### ISSUE THREAD

**Issue by kudosforanuget** [mike-mo/MoreTerra#14]
![image](https://user-images.githubusercontent.com/15146301/39966073-a48f03b0-5673-11e8-9e02-fc183a1f878b.png)

**Comment by mike-mo** [comment]
We haven't kept up with Terraria updates for a couple of months. Do you want to help fix this?

**Comment by Walkman100** [comment]
For now you can work around this by unchecking `People` in the Markers tab

**Comment by bevig64** [comment]
> For now you can work around this by unchecking `People` in the Markers tab

oh thank you for the question~

**Comment by AxeOfMen** [comment]
I took a stab at fixing this error. Here is my pull request:
#19

**Comment by mike-mo** [comment]
Release created: https://github.com/mike-mo/MoreTerra/releases/tag/v1.16
