### ISSUE TITLE
Incompatible with Terraria 1.3 Update.

### ISSUE THREAD

**Issue by imasonaz** [mike-mo/MoreTerra#2]
When loading a 1.3 world, MoreTerra crashes with the attached error.
![image](https://cloud.githubusercontent.com/assets/5715364/8456106/06118616-1fbe-11e5-8641-f3a70d09eba7.png)

**Comment by talliansaotome** [comment]
I am simply unable to load the world, with 'World Name: Not a valid World file.', and I am unable to select a different world.

**Comment by TerabyteRex** [comment]
We are in the process. There were huge changes the the wld file header. Will update when done.

We hope to get this out soon.

Sent from my Windows Phone

**Comment by Pysis868** [comment]
Just to note, I am running Terraria 1.3.4.4, and MoreTerra 1.13.

I did not receive this error, but instead, this one in #6: "Error Opening World: Parameter name: dateData"

The issue title should probably be more descriptive, such as: "Error Opening World: Unable to read beyond the end of the stream."

**Comment by zauberparacelsus** [comment]
As far as I can tell, this project is no longer being maintained.  For now, I'd recommend using Terra Firma as a replacement.

**Comment by TerabyteRex** [comment]
this is now fixed, please get latest binary
