### ISSUE TITLE
Running updated version

### ISSUE THREAD

**Issue by deepslater** [mike-mo/MoreTerra#3]
Do you need Git/Github clients to run the new program from github? I can't find a .exe in the downloaded folder.

**Comment by zauberparacelsus** [comment]
You downloaded the source code.  You'll need to compile it.

**Comment by deepslater** [comment]
That's frustrating, considering you used to be able to download the already-compiled app.

**Comment by zauberparacelsus** [comment]
What's more frustrating is that I don't see any instructions for compiling.

**Comment by zauberparacelsus** [comment]
Okay, building it with Visual Studio was fairly straightforward.  Here's a link to the build I compiled.  With a quick test on a 1.3 world it seems to work.  It's a debug build though, so it may be a little slower (though it completed scanning a large world within a few seconds for me, so maybe not)
https://mega.nz/#!2l0h1DpA!grecpjA224zF0SHbzUpzssVHGj9tYLTIOmEBFe_JhXQ

**Comment by TerabyteRex** [comment]
We are working on getting the option to download the compiled exe. Sorry for the inconvenience.

Sent from my Windows Phone

**Comment by deepslater** [comment]
Works great, thanks! I couldn't bother figuring out how to compile it...

**Comment by zauberparacelsus** [comment]
It was fairly easy, actually.  I went into the WorldView folder, opened the MoreTerra.sln file in Visual Studio 2013 (community edition, which is free), and then used the Build Solution option from the Build menu.  The results were placed in the WorldView/bin/debug folder

**Comment by Pysis868** [comment]
I now see the link for downloading binaries under Code > [Releases](https://github.com/mike-mo/MoreTerra/releases).

Here is an example for [MoraTerra 1.13](https://github.com/mike-mo/MoreTerra/releases/tag/1.13) [binaries](https://github.com/mike-mo/MoreTerra/releases/download/1.13/MoreTerra_Binaries.zip).

Maybe this issue can be closed now.

Also, rename the title to talk about how to compile the source code.
