### ISSUE TITLE
Terraria 1.3.3

### ISSUE THREAD

**Issue by zauberparacelsus** [mike-mo/MoreTerra#6]
Terraria 1.3.3 is out, and it looks like MoreTerra doesn't work with it.  I get an overflow exception

**Comment by randrade86** [comment]
![image](https://cloud.githubusercontent.com/assets/5365488/20502577/d27318a2-b025-11e6-8fe4-2b06a83eb639.png)

**Comment by Pysis868** [comment]
I have Terraria version 1.3.4.4, and I believe I have the same error.  Uploading another screenshot in the possibly more convenient English language:
![image](https://cloud.githubusercontent.com/assets/1408565/21486489/8c80ba42-cb83-11e6-88f7-667b703ee54c.png)

The main window did correctly represent that the "Draw World" action may not work, although the UI did make this *very* obvious or direct with the text "Not a valid World file":
![image](https://cloud.githubusercontent.com/assets/1408565/21486513/e595e472-cb83-11e6-9343-0c5012d320c1.png)

Just posting with more information, and thinking the fix would be to update the world parser for the newer version of Terraria.



O, and the issue title should probably be more descriptive, such as: "Error Opening World: Parameter name: dateData"

**Comment by TerabyteRex** [comment]
looking to update it shortly

**Comment by TerabyteRex** [comment]
This has now been fixed please get latest binary.
