### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Anon411** [mike-mo/MoreTerra#8]
Getting the following message when trying to use:
---------------------------
Error Opening World
---------------------------
Arithmetic operation resulted in an overflow.

Details: System.OverflowException: Arithmetic operation resulted in an overflow.

   at MoreTerra.Structures.World.ReadAndProcessWorld(String worldPath, BackgroundWorker worker)

   at MoreTerra.WorldMapper.ProcessWorld(String worldPath, BackgroundWorker bw)

   at MoreTerra.FormWorldView.worker_GenerateMap(Object sender, DoWorkEventArgs e)

Version: 1.13
---------------------------
OK   
---------------------------

**Comment by vgezer** [comment]
I get the same error. Probably something changed after the update. I can draw my old map.

**Comment by TerabyteRex** [comment]
MoreTerra will need to be updated for new version of terraria. I will start looking into it. I honestly didn't know it was still being used.

**Comment by TerabyteRex** [comment]
This has now been fixed, please download latest binary

**Comment by vgezer** [comment]
Great! Thanks for the fix. Yes we still use it :p

**Comment by Anon411** [comment]
I echo the past post  - yes I still use it and thanks so much for the update(s).

If you use steam as a back up for your worlds, isnt that data also on your computer system?  I cant seem to find the worlds anymore.
